@echo off
rem ===========================================================================
rem  SafiriConnect - one-click launcher
rem
rem  Double-click this file. It checks everything the app needs, starts it, and
rem  opens the browser. Close this window, or press Ctrl+C, to stop the server.
rem
rem  This is one Next.js process serving both the site and its API from a local
rem  SQLite file - there is no separate backend, frontend or database server to
rem  start, which is why a single launcher is enough.
rem
rem  Note on style: every explanatory message lives at a label at the bottom,
rem  never inside an if(...) block. A closing bracket in a message such as
rem  ENOSPC would otherwise be read as the end of the block and crash the
rem  script - which is exactly the bug this version fixes.
rem ===========================================================================

setlocal enableextensions
title SafiriConnect
color 0A

rem Run from the project folder no matter where the file was launched from, so
rem the config files and the database resolve correctly.
cd /d "%~dp0"

set "PORT=3000"
set "URL=http://localhost:%PORT%"

echo(
echo   ============================================================
echo      SafiriConnect  -  starting up
echo   ============================================================
echo(

rem --------------------------------------------------------------------- Node
echo   [1/6] Checking Node.js...
where node >nul 2>nul || goto :err_node
for /f "delims=" %%v in ('node -v') do set "NODEV=%%v"
echo         Node.js %NODEV% found.

rem ---------------------------------------------------------------- .env file
echo   [2/6] Checking configuration...
if exist ".env" goto :env_ok
if not exist ".env.example" goto :env_default
copy /y ".env.example" ".env" >nul
echo         Created .env from the template.
goto :deps
:env_default
echo         WARNING: no .env or .env.example - using built-in defaults.
goto :deps
:env_ok
echo         Configuration present.

rem ------------------------------------------------------------- dependencies
:deps
echo   [3/6] Checking dependencies...
if exist "node_modules" goto :deps_ok
echo         First run - installing packages. This can take a few minutes...
call npm install
if errorlevel 1 goto :err_install
goto :database
:deps_ok
echo         Dependencies installed.

rem ------------------------------------------------------------------ database
:database
echo   [4/6] Checking database...
if exist "prisma\dev.db" goto :db_ok
echo(
echo         No database found - creating and loading demo data.
echo         This happens only once and takes about 4 minutes. Please wait...
echo(
call npm run setup
if errorlevel 1 goto :err_db
goto :build
:db_ok
echo         Database ready.

rem -------------------------------------------------------------------- build
:build
echo   [5/6] Preparing the application...
if exist ".next\BUILD_ID" goto :build_ok
echo         Building for the first time - about a minute. Please wait...
rem Build with Next directly rather than "npm run build". The build script also
rem runs "prisma generate", which renames the query-engine DLL - and that rename
rem fails with EPERM whenever another Node process (a dev server, an editor's
rem terminal) has the engine loaded. The Prisma client is already generated by
rem the setup step, so the rename is unnecessary here and only adds a way to
rem fail. next build merely reads the engine, which a lock never blocks.
call "node_modules\.bin\next.cmd" build
if errorlevel 1 goto :err_build
goto :launch
:build_ok
echo         Build present - starting immediately.

rem ------------------------------------------------------------------- launch
:launch
echo   [6/6] Starting the server...
echo(

rem A detached waiter polls the port and opens the browser the moment the
rem server answers, so the page never loads before it is ready. Kept to one
rem line, with no pipe, so cmd does not need to escape anything.
start "" /b powershell -NoProfile -ExecutionPolicy Bypass -Command "for($i=0;$i -lt 90;$i++){ try{ $null = Invoke-WebRequest '%URL%' -UseBasicParsing -TimeoutSec 2; Start-Process '%URL%'; break }catch{ Start-Sleep -Seconds 1 } }"

echo   ------------------------------------------------------------
echo     SafiriConnect is starting at  %URL%
echo     The browser opens automatically once it is ready.
echo(
echo     Sign in with:
echo       Super admin    admin@safiriconnect.co.ke    / Password123
echo       Booking staff  staff@safiriconnect.co.ke    / Password123
echo       Passenger      passenger@example.com        / Password123
echo(
echo     Open a second tab and sign in as a different account to
echo     demonstrate the per-tab sessions.
echo(
echo     Keep this window open. Close it, or press Ctrl+C, to stop.
echo   ------------------------------------------------------------
echo(

rem Runs in the foreground and holds the window open; the server lives here.
call npm run start
goto :stopped

rem =========================================================================
rem  Messages. These live outside every block, so they may contain any text.
rem =========================================================================

:err_node
echo(
echo   ERROR: Node.js is not installed, or not on your PATH.
echo(
echo   SafiriConnect needs Node.js 18 or newer. Install the LTS build from
echo   https://nodejs.org/ then double-click this file again.
goto :fail

:err_install
echo(
echo   ERROR: installing dependencies failed.
echo   The usual cause is no internet connection or a full disk. Check both,
echo   then run this file again.
goto :fail

:err_db
echo(
echo   ERROR: setting up the database failed.
echo   If the message above mentioned ENOSPC, the disk is full - free some
echo   space and try again.
goto :fail

:err_build
echo(
echo   ERROR: the build failed. Scroll up for the reason.
echo(
echo   Two common causes on this machine:
echo     - SafiriConnect is already running in another window. Close it first,
echo       so this launcher is the only copy using the app and its database.
echo     - The disk is full, shown above as ENOSPC. Free some space.
goto :fail

:fail
echo(
echo   Startup stopped. Read the message above, fix it, and run this file again.
echo(
pause
exit /b 1

:stopped
echo(
echo   SafiriConnect has stopped.
echo(
pause
endlocal
