import { db } from "@/lib/db";
import { handler, ok, parseBody, requireCapability, badRequest } from "@/lib/api";
import { operatorScope, assertSameOperator } from "@/lib/scope";
import { generateFromTemplate, generateAll } from "@/lib/schedules";
import { audit } from "@/lib/audit";
import { z } from "zod";

/**
 * Recurring schedule administration.
 *
 * This is the gap that has been open since the availability calendar was built:
 * departures could be generated by the seed but not created or edited by an
 * administrator, so "add a bus for the festive season" meant editing a script.
 */

export async function GET(req: Request) {
  return handler(async () => {
    const user = await requireCapability("MANAGE_SCHEDULE", req);
    const scope = operatorScope(user);

    const schedules = await db.scheduleTemplate.findMany({
      where: scope ? { operatorId: scope } : {},
      orderBy: [{ isActive: "desc" }, { departureTime: "asc" }],
      select: {
        id: true,
        daysOfWeek: true,
        departureTime: true,
        fare: true,
        validFrom: true,
        validTo: true,
        isActive: true,
        route: { select: { id: true, origin: true, destination: true } },
        bus: { select: { id: true, registration: true, model: true, capacity: true } },
        driverId: true,
        conductorId: true,
        operator: { select: { name: true, code: true } },
        _count: { select: { trips: true } },
      },
    });

    return ok({
      schedules: schedules.map((s) => ({
        ...s,
        daysOfWeek: JSON.parse(s.daysOfWeek) as number[],
        corridor: `${s.route.origin} – ${s.route.destination}`,
      })),
    });
  });
}

const scheduleSchema = z.object({
  routeId: z.string().min(1),
  busId: z.string().min(1),
  driverId: z.string().nullable().optional(),
  conductorId: z.string().nullable().optional(),
  /** 0 = Sunday, matching JavaScript's getDay. */
  daysOfWeek: z.array(z.number().int().min(0).max(6)).min(1),
  departureTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Use HH:mm, e.g. 07:30."),
  fare: z.number().int().positive(),
  validFrom: z.coerce.date().optional(),
  validTo: z.coerce.date().nullable().optional(),
  /** Publish departures immediately rather than waiting for the next run. */
  generate: z.boolean().optional().default(true),
});

export async function POST(req: Request) {
  return handler(async () => {
    const user = await requireCapability("MANAGE_SCHEDULE", req);
    const data = await parseBody(req, scheduleSchema);

    const bus = await db.bus.findUnique({
      where: { id: data.busId },
      select: { operatorId: true, status: true },
    });
    if (!bus) throw badRequest("That bus is not on the fleet.");
    if (bus.status !== "ACTIVE") throw badRequest("That bus is not in service.");

    assertSameOperator(user, bus.operatorId);

    const operatorId = operatorScope(user) ?? bus.operatorId;
    if (!operatorId) {
      throw badRequest("That bus is not assigned to a transport company.");
    }

    const template = await db.scheduleTemplate.create({
      data: {
        operatorId,
        routeId: data.routeId,
        busId: data.busId,
        driverId: data.driverId ?? null,
        conductorId: data.conductorId ?? null,
        daysOfWeek: JSON.stringify([...new Set(data.daysOfWeek)].sort()),
        departureTime: data.departureTime,
        fare: data.fare,
        validFrom: data.validFrom ?? new Date(),
        validTo: data.validTo ?? null,
      },
    });

    await audit({
      userId: user.id,
      operatorId,
      action: "SCHEDULE_CREATE",
      entity: "ScheduleTemplate",
      entityId: template.id,
      metadata: data,
      req,
    });

    // Publishing straight away is what makes the calendar reflect the new
    // service on the next page load rather than at some unspecified later time.
    const generated = data.generate ? await generateFromTemplate(template.id) : null;

    return ok({ schedule: template, generated }, 201);
  });
}

/** Re-runs generation, extending the published horizon. */
export async function PUT(req: Request) {
  return handler(async () => {
    const user = await requireCapability("MANAGE_SCHEDULE", req);
    const result = await generateAll(operatorScope(user));

    await audit({
      userId: user.id,
      operatorId: operatorScope(user),
      action: "SCHEDULE_GENERATE",
      entity: "ScheduleTemplate",
      metadata: result,
      req,
    });

    return ok(result);
  });
}
