"use client";

import { useCallback, useEffect, useState } from "react";
import { Repeat, Plus, CalendarClock, RefreshCw, Bus as BusIcon } from "lucide-react";
import { api, KES } from "@/lib/client";
import { cx, Spinner, EmptyState } from "@/components/ui";
import { useLive } from "@/components/live";
import { toast } from "sonner";

/**
 * Recurring timetable administration.
 *
 * The gap this closes has been open since the availability calendar was built:
 * departures could be generated by the seed script but never created from the
 * interface, so adding a bus for the festive season meant editing code.
 *
 * A template is the pattern — "the 07:00 to Mombasa, weekdays" — and generation
 * projects it into real departures on a rolling horizon.
 */

const DAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

type Schedule = {
  id: string;
  corridor: string;
  daysOfWeek: number[];
  departureTime: string;
  fare: number;
  isActive: boolean;
  validFrom: string;
  validTo: string | null;
  route: { id: string; origin: string; destination: string };
  bus: { id: string; registration: string; model: string; capacity: number } | null;
  operator: { name: string; code: string };
  _count: { trips: number };
};

type BusOption = { id: string; registration: string; model: string; capacity: number };
type RouteOption = { id: string; origin: string; destination: string; baseFare: number };

export function SchedulesAdmin() {
  const [schedules, setSchedules] = useState<Schedule[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [generating, setGenerating] = useState(false);

  const load = useCallback((showSpinner = false) => {
    if (showSpinner) setLoading(true);
    api<{ schedules: Schedule[] }>("/api/schedules")
      .then((d) => setSchedules(d.schedules))
      .catch(() => setSchedules(null))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load(true);
  }, [load]);

  useLive(["trip.cancelled"], () => load(false), { pollMs: 0 });

  async function generate() {
    setGenerating(true);
    try {
      const result = await api<{ templates: number; created: number; skipped: number }>(
        "/api/schedules",
        { method: "PUT" },
      );
      toast.success(`${result.created} departure(s) published`, {
        description: result.skipped
          ? `${result.skipped} already existed or clashed with another booking.`
          : `From ${result.templates} schedule(s).`,
      });
      load(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Generation failed.");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold tracking-tight text-ink">Recurring schedules</h1>
          <p className="mt-1 text-sm text-muted">
            The patterns that publish your timetable. Departures are generated 30 days ahead.
          </p>
        </div>

        <div className="flex gap-2">
          <button onClick={generate} disabled={generating} className="btn-secondary">
            <RefreshCw className={cx("h-4 w-4", generating && "animate-spin")} />
            Publish departures
          </button>
          <button onClick={() => setCreating(true)} className="btn-primary">
            <Plus className="h-4 w-4" /> New schedule
          </button>
        </div>
      </div>

      {creating && (
        <CreateForm
          onClose={() => setCreating(false)}
          onCreated={() => {
            setCreating(false);
            load(false);
          }}
        />
      )}

      {loading ? (
        <div className="grid place-items-center py-20">
          <Spinner className="h-6 w-6 text-brand" />
        </div>
      ) : !schedules?.length ? (
        <div className="card">
          <EmptyState
            icon={<Repeat className="h-6 w-6" aria-hidden />}
            title="No recurring schedules"
            description="Create one to publish a departure that repeats, instead of adding each one by hand."
          />
        </div>
      ) : (
        <div className="grid gap-3">
          {schedules.map((s) => (
            <article key={s.id} className="card flex flex-col gap-4 p-5 lg:flex-row lg:items-center">
              <div className="text-center lg:w-20">
                <p className="text-xl font-extrabold tracking-tight text-ink">{s.departureTime}</p>
                <p className="text-[10px] uppercase tracking-wide text-muted">daily</p>
              </div>

              <div className="min-w-0 flex-1">
                <p className="font-bold text-ink">{s.corridor}</p>
                <p className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted">
                  {s.bus && (
                    <span className="flex items-center gap-1">
                      <BusIcon className="h-3.5 w-3.5" /> {s.bus.registration} · {s.bus.model}
                    </span>
                  )}
                  <span className="flex items-center gap-1">
                    <CalendarClock className="h-3.5 w-3.5" /> {s._count.trips} published
                  </span>
                </p>

                <div className="mt-2 flex gap-1">
                  {DAY_LABELS.map((label, day) => (
                    <span
                      key={day}
                      className={cx(
                        "grid h-6 w-8 place-items-center rounded text-[10px] font-bold",
                        s.daysOfWeek.includes(day)
                          ? "bg-brand-soft text-brand"
                          : "bg-elevated text-muted/40",
                      )}
                    >
                      {label}
                    </span>
                  ))}
                </div>
              </div>

              <div className="flex items-center justify-between gap-4 border-t border-line pt-4 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0 lg:text-right">
                <div>
                  <p className="text-lg font-extrabold text-brand">{KES(s.fare)}</p>
                  <p className="text-[11px] text-muted">per seat</p>
                </div>
                <span
                  className={cx(
                    "badge",
                    s.isActive ? "bg-ok/15 text-ok" : "bg-elevated text-muted",
                  )}
                >
                  {s.isActive ? "active" : "paused"}
                </span>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}

function CreateForm({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const [buses, setBuses] = useState<BusOption[]>([]);
  const [routes, setRoutes] = useState<RouteOption[]>([]);
  const [busId, setBusId] = useState("");
  const [routeId, setRouteId] = useState("");
  const [days, setDays] = useState<number[]>([1, 2, 3, 4, 5]);
  const [time, setTime] = useState("07:00");
  const [fare, setFare] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    api<{ buses: BusOption[] }>("/api/buses?status=ACTIVE")
      .then((d) => setBuses(d.buses))
      .catch(() => setBuses([]));
    api<{ routes: RouteOption[] }>("/api/routes?perPage=500")
      .then((d) => setRoutes(d.routes))
      .catch(() => setRoutes([]));
  }, []);

  // Pre-fill the fare from the corridor's market rate, so a schedule is never
  // created unpriced and the operator starts from a sensible number.
  useEffect(() => {
    const route = routes.find((r) => r.id === routeId);
    if (route && !fare) setFare(String(route.baseFare));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [routeId, routes]);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    try {
      const result = await api<{ generated: { created: number } | null }>("/api/schedules", {
        method: "POST",
        body: JSON.stringify({
          routeId,
          busId,
          daysOfWeek: days,
          departureTime: time,
          fare: Number(fare),
          generate: true,
        }),
      });
      toast.success("Schedule created", {
        description: result.generated
          ? `${result.generated.created} departure(s) published.`
          : undefined,
      });
      onCreated();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "That did not work.");
    } finally {
      setSaving(false);
    }
  }

  return (
    <form onSubmit={submit} className="card space-y-4 p-5">
      <div className="grid gap-4 sm:grid-cols-2">
        <label className="block">
          <span className="mb-1 block text-xs font-semibold text-muted">Route</span>
          <select
            required
            value={routeId}
            onChange={(e) => setRouteId(e.target.value)}
            className="input"
          >
            <option value="">Choose a corridor…</option>
            {routes.map((r) => (
              <option key={r.id} value={r.id}>
                {r.origin} – {r.destination}
              </option>
            ))}
          </select>
        </label>

        <label className="block">
          <span className="mb-1 block text-xs font-semibold text-muted">Bus</span>
          <select required value={busId} onChange={(e) => setBusId(e.target.value)} className="input">
            <option value="">Choose a vehicle…</option>
            {buses.map((b) => (
              <option key={b.id} value={b.id}>
                {b.registration} · {b.model} ({b.capacity} seats)
              </option>
            ))}
          </select>
        </label>

        <label className="block">
          <span className="mb-1 block text-xs font-semibold text-muted">Departure time</span>
          <input
            required
            type="time"
            value={time}
            onChange={(e) => setTime(e.target.value)}
            className="input"
          />
        </label>

        <label className="block">
          <span className="mb-1 block text-xs font-semibold text-muted">Fare (Ksh)</span>
          <input
            required
            type="number"
            min={1}
            value={fare}
            onChange={(e) => setFare(e.target.value)}
            className="input"
          />
        </label>
      </div>

      <div>
        <span className="mb-1.5 block text-xs font-semibold text-muted">Runs on</span>
        <div className="flex flex-wrap gap-1.5">
          {DAY_LABELS.map((label, day) => (
            <button
              key={day}
              type="button"
              onClick={() =>
                setDays((prev) =>
                  prev.includes(day) ? prev.filter((d) => d !== day) : [...prev, day],
                )
              }
              className={cx(
                "rounded-lg border px-3 py-1.5 text-xs font-semibold transition",
                days.includes(day)
                  ? "border-brand/30 bg-brand-soft text-brand"
                  : "border-line text-muted hover:text-ink",
              )}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      <div className="flex justify-end gap-2 border-t border-line pt-4">
        <button type="button" onClick={onClose} className="btn-secondary">
          Cancel
        </button>
        <button type="submit" disabled={saving || !days.length} className="btn-primary">
          {saving ? <Spinner className="h-4 w-4" /> : <Plus className="h-4 w-4" />}
          Create and publish
        </button>
      </div>
    </form>
  );
}
